### ISSUE TITLE
stats error 

### ISSUE THREAD

**Issue by rpkaul** [DistrictNineHost/RankMe-Discord-Web#3]
can you please fix this stats error??

when i am opening stats from home page its showing me 0(zero) for all players
https://lotgaming.xyz/test/profile.php?id=STEAM_1:0:82917173

its showing fine here
https://lotgaming.xyz/test/leaderboard.php

**Comment by WardPearce** [comment]
Yea I'll get onto it, thanks for pointing it out.

**Comment by WardPearce** [comment]
Should be fixed.
